name: "Deployment"

on: 
  workflow_dispatch:  # allows manual trigger
  push:
    branches:
      - master
    paths-ignore:
      - "Docs/**"
      - "Contribution/**"
      - ".github/**"
      - ".gitignore"
      - "README.md"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # required to push to GHCR
      id-token: write  # optional if using OIDC auth
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check if secret exists
        run: |
          if [ -z "${{ secrets.TOKEN_GITHUB }}" ]; then
            echo "TOKEN_GITHUB is empty!"
          else
            echo "TOKEN_GITHUB is set!"
          fi

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: abdualrimali
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/greencode101/scholarmind/backend:latest ./backend

      - name: Push Docker image
        run: |
          docker push ghcr.io/greencode101/scholarmind/backend:latest


